[package]
name = "mechaflt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
include_dir = "0.7.4"
inquire = "0.7.5"
uuu-rs = { path = "../lib/uuu-rs" }
